# Generated by Django 3.2.3 on 2021-08-18 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210817_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='language',
            field=models.CharField(blank=True, max_length=128, verbose_name='теги'),
        ),
        migrations.AddField(
            model_name='shopuserprofile',
            name='vk_profile',
            field=models.CharField(blank=True, max_length=128, verbose_name='теги'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 13, 59, 35, 894382)),
        ),
    ]
