# Generated by Django 3.2.3 on 2021-08-18 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20210818_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 14, 10, 39, 248635)),
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='language',
            field=models.CharField(blank=True, max_length=128, verbose_name='язык'),
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='vk_profile',
            field=models.CharField(blank=True, max_length=128, verbose_name='профиль ВК'),
        ),
    ]
