# Generated by Django 3.2.3 on 2021-08-20 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='ok_profile',
            field=models.CharField(blank=True, max_length=128, verbose_name='профиль Одноклассник'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 13, 48, 55, 967624)),
        ),
    ]
