# Generated by Django 3.2.3 on 2021-08-23 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_auto_20210820_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 14, 46, 48, 285925)),
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='ok_profile',
            field=models.CharField(blank=True, max_length=128, verbose_name='профиль Одноклассники'),
        ),
    ]
